list(APPEND detex_sources
    detex/bptc-tables.c     
    detex/bits.c               
    detex/clamp.c             
    detex/convert.c            
    detex/dds.c                
    detex/decompress-bc.c      
    detex/decompress-bptc.c     
    detex/decompress-bptc-float.c 
    detex/decompress-etc.c 
    detex/decompress-eac.c 
    detex/decompress-rgtc.c 
    detex/division-tables.c  
    detex/file-info.c    
    detex/half-float.c
    detex/hdr.c
    detex/ktx.c
    detex/misc.c
    detex/raw.c
    detex/texture.c
)
